/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppArchetypesRouteImport } from './routes/_authenticated/_app/archetypes'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/_app/audit'
import { Route as AuthenticatedAppClustersRouteImport } from './routes/_authenticated/_app/clusters'
import { Route as AuthenticatedAppCoverageRouteImport } from './routes/_authenticated/_app/coverage'
import { Route as AuthenticatedAppCredentialsRouteImport } from './routes/_authenticated/_app/credentials'
import { Route as AuthenticatedAppJourneysRouteImport } from './routes/_authenticated/_app/journeys'
import { Route as AuthenticatedAppOverviewRouteImport } from './routes/_authenticated/_app/overview'
import { Route as AuthenticatedAppReleasesRouteImport } from './routes/_authenticated/_app/releases'
import { Route as AuthenticatedAppRunsRouteImport } from './routes/_authenticated/_app/runs'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppArchetypesRoute =
  AuthenticatedAppArchetypesRouteImport.update({
    id: '/archetypes',
    path: '/archetypes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClustersRoute =
  AuthenticatedAppClustersRouteImport.update({
    id: '/clusters',
    path: '/clusters',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoverageRoute =
  AuthenticatedAppCoverageRouteImport.update({
    id: '/coverage',
    path: '/coverage',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCredentialsRoute =
  AuthenticatedAppCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppJourneysRoute =
  AuthenticatedAppJourneysRouteImport.update({
    id: '/journeys',
    path: '/journeys',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOverviewRoute =
  AuthenticatedAppOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReleasesRoute =
  AuthenticatedAppReleasesRouteImport.update({
    id: '/releases',
    path: '/releases',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRunsRoute = AuthenticatedAppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/archetypes': typeof AuthenticatedAppArchetypesRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/clusters': typeof AuthenticatedAppClustersRoute
  '/coverage': typeof AuthenticatedAppCoverageRoute
  '/credentials': typeof AuthenticatedAppCredentialsRoute
  '/journeys': typeof AuthenticatedAppJourneysRoute
  '/overview': typeof AuthenticatedAppOverviewRoute
  '/releases': typeof AuthenticatedAppReleasesRoute
  '/runs': typeof AuthenticatedAppRunsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/archetypes': typeof AuthenticatedAppArchetypesRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/clusters': typeof AuthenticatedAppClustersRoute
  '/coverage': typeof AuthenticatedAppCoverageRoute
  '/credentials': typeof AuthenticatedAppCredentialsRoute
  '/journeys': typeof AuthenticatedAppJourneysRoute
  '/overview': typeof AuthenticatedAppOverviewRoute
  '/releases': typeof AuthenticatedAppReleasesRoute
  '/runs': typeof AuthenticatedAppRunsRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/_app/archetypes': typeof AuthenticatedAppArchetypesRoute
  '/_authenticated/_app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/_app/clusters': typeof AuthenticatedAppClustersRoute
  '/_authenticated/_app/coverage': typeof AuthenticatedAppCoverageRoute
  '/_authenticated/_app/credentials': typeof AuthenticatedAppCredentialsRoute
  '/_authenticated/_app/journeys': typeof AuthenticatedAppJourneysRoute
  '/_authenticated/_app/overview': typeof AuthenticatedAppOverviewRoute
  '/_authenticated/_app/releases': typeof AuthenticatedAppReleasesRoute
  '/_authenticated/_app/runs': typeof AuthenticatedAppRunsRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/archetypes'
    | '/audit'
    | '/clusters'
    | '/coverage'
    | '/credentials'
    | '/journeys'
    | '/overview'
    | '/releases'
    | '/runs'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/archetypes'
    | '/audit'
    | '/clusters'
    | '/coverage'
    | '/credentials'
    | '/journeys'
    | '/overview'
    | '/releases'
    | '/runs'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/_authenticated/_app/archetypes'
    | '/_authenticated/_app/audit'
    | '/_authenticated/_app/clusters'
    | '/_authenticated/_app/coverage'
    | '/_authenticated/_app/credentials'
    | '/_authenticated/_app/journeys'
    | '/_authenticated/_app/overview'
    | '/_authenticated/_app/releases'
    | '/_authenticated/_app/runs'
    | '/_authenticated/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/archetypes': {
      id: '/_authenticated/_app/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof AuthenticatedAppArchetypesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/audit': {
      id: '/_authenticated/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/clusters': {
      id: '/_authenticated/_app/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof AuthenticatedAppClustersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/coverage': {
      id: '/_authenticated/_app/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AuthenticatedAppCoverageRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/credentials': {
      id: '/_authenticated/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthenticatedAppCredentialsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/journeys': {
      id: '/_authenticated/_app/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof AuthenticatedAppJourneysRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/overview': {
      id: '/_authenticated/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedAppOverviewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/releases': {
      id: '/_authenticated/_app/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof AuthenticatedAppReleasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/runs': {
      id: '/_authenticated/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedAppRunsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppArchetypesRoute: typeof AuthenticatedAppArchetypesRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppClustersRoute: typeof AuthenticatedAppClustersRoute
  AuthenticatedAppCoverageRoute: typeof AuthenticatedAppCoverageRoute
  AuthenticatedAppCredentialsRoute: typeof AuthenticatedAppCredentialsRoute
  AuthenticatedAppJourneysRoute: typeof AuthenticatedAppJourneysRoute
  AuthenticatedAppOverviewRoute: typeof AuthenticatedAppOverviewRoute
  AuthenticatedAppReleasesRoute: typeof AuthenticatedAppReleasesRoute
  AuthenticatedAppRunsRoute: typeof AuthenticatedAppRunsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppArchetypesRoute: AuthenticatedAppArchetypesRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppClustersRoute: AuthenticatedAppClustersRoute,
  AuthenticatedAppCoverageRoute: AuthenticatedAppCoverageRoute,
  AuthenticatedAppCredentialsRoute: AuthenticatedAppCredentialsRoute,
  AuthenticatedAppJourneysRoute: AuthenticatedAppJourneysRoute,
  AuthenticatedAppOverviewRoute: AuthenticatedAppOverviewRoute,
  AuthenticatedAppReleasesRoute: AuthenticatedAppReleasesRoute,
  AuthenticatedAppRunsRoute: AuthenticatedAppRunsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
